platform :ios, '10.0'
use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'https://github.com/applicaster/applicaster-iap-framework'

target 'CAMFramework' do
  pod 'CAM', :path => '../CAM.podspec'
end
